import { useState } from "react";
import { Link, useNavigate, Navigate } from "react-router";
import AuthLayout from "../components/AuthLayout";
import GoogleSignInButton from "../components/GoogleSignInButton";
import { Field, TextInput } from "../../../shared/components/Field";
import Button from "../../../shared/components/Button";
import Callout from "../../../shared/components/Callout";
import PageLoader from "../../../shared/components/PageLoader";
import { useAuth } from "../hooks/useAuth";
import "../auth.form.scss";
const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const Login = () => { const navigate = useNavigate(); const { user, loading, handleLogin, handleGoogleAuth } = useAuth(); const [email,setEmail]=useState(()=>localStorage.getItem("ra_saved_email")||""); const [password,setPassword]=useState(""); const [rememberMe,setRememberMe]=useState(()=>Boolean(localStorage.getItem("ra_saved_email"))); const [error,setError]=useState(""); const [emailError,setEmailError]=useState(""); const [submitting,setSubmitting]=useState(false);
if(!loading&&user)return <Navigate to="/analyze/ats-score" replace/>;
const submit=async(e)=>{e.preventDefault();setError("");const mailErr=!email?"Email is required":!EMAIL_REGEX.test(email.trim())?"Please enter a valid email address":"";if(mailErr){setEmailError(mailErr);return}if(!password){setError("Please enter your password");return}setSubmitting(true);try{if(rememberMe)localStorage.setItem("ra_saved_email",email.trim());else localStorage.removeItem("ra_saved_email");await handleLogin({email:email.trim(),password});navigate("/analyze/ats-score")}catch(err){setError(err.response?.data?.message||err.message||"Invalid credentials.")}finally{setSubmitting(false)}};
const google=async(credential)=>{setError("");try{await handleGoogleAuth(credential);navigate("/analyze/ats-score")}catch(err){setError(err.response?.data?.message||err.message||"Google sign-in failed.")}};
if(loading)return <PageLoader label="Verifying session credentials"/>;
return <AuthLayout eyebrow="Welcome back" title="Sign in to your account">{error&&<Callout tone="error">{error}</Callout>}<GoogleSignInButton onCredential={google} disabled={submitting}/><div className="auth-form__divider"><span>or sign in with email</span></div><form className="auth-form" onSubmit={submit} noValidate><Field label="Email address" htmlFor="email" error={emailError} required><TextInput id="email" type="email" autoComplete="email" autoFocus placeholder="name@domain.com" value={email} onChange={e=>{setEmail(e.target.value);setEmailError("");setError("")}} required disabled={submitting}/></Field><Field label="Password" htmlFor="password" required><TextInput id="password" type="password" autoComplete="current-password" placeholder="Enter your password" value={password} onChange={e=>{setPassword(e.target.value);setError("")}} required disabled={submitting}/></Field><div className="auth-form__options"><label className="auth-form__checkbox-label"><input type="checkbox" className="auth-form__checkbox" checked={rememberMe} onChange={e=>setRememberMe(e.target.checked)} disabled={submitting}/><span>Remember email</span></label><Link to="/forgot-password">Forgot password?</Link></div><Button type="submit" size="lg" variant="primary" loading={submitting} disabled={submitting||!email.trim()||!password} className="auth-form__submit">{submitting?"Authenticating…":"Sign in"}</Button></form><p className="auth-form__switch">Don't have an account yet? <Link to="/register">Create an account</Link></p></AuthLayout>};
export default Login;
