import api from "../../../shared/api/client";

/**
 * Upload resume PDF or send resume text to be analyzed for ATS compatibility
 */
export async function analyzeAtsResume({ resume, resumeText, fileName }) {
  if (resume) {
    const formData = new FormData();
    formData.append("resume", resume);
    const response = await api.post("/api/resume/ats-analyze", formData, {
      headers: { "Content-Type": "multipart/form-data" },
    });
    return response.data;
  }

  const response = await api.post("/api/resume/ats-analyze", {
    resume: resumeText,
    fileName: fileName || "Pasted-Resume.txt",
  });
  return response.data;
}

/**
 * Call AI to rewrite/fix resume sections according to ATS recommendations
 */
export async function reviseAtsResume({ id, sections = "all", customNotes = "" }) {
  const response = await api.post("/api/resume/ats-revise", {
    id,
    sections,
    customNotes,
  });
  return response.data;
}

/**
 * Retrieve saved ATS report and revised resume data by session ID
 */
export async function getAtsReportById(id) {
  const response = await api.get(`/api/resume/ats-report/${id}`);
  return response.data;
}

/**
 * Fetch ATS PDF as a Blob URL for inline iframe preview
 */
export async function fetchAtsPdfBlobUrl(id) {
  const response = await api.get(`/api/resume/ats-download/${id}`, {
    responseType: "blob",
  });
  const blob = new Blob([response.data], { type: "application/pdf" });
  return window.URL.createObjectURL(blob);
}

/**
 * Download ATS-optimized PDF generated by Puppeteer
 */
export async function downloadAtsPdf(id, candidateName = "ATS-Resume") {
  const response = await api.get(`/api/resume/ats-download/${id}`, {
    responseType: "blob",
  });

  const blob = new Blob([response.data], { type: "application/pdf" });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  const safeName = (candidateName || "ATS-Resume").replace(/[^a-zA-Z0-9_-]/g, "_");
  link.download = `${safeName}_ATS_Optimized.pdf`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.URL.revokeObjectURL(url);
}
